### ISSUE TITLE
Fix scrollbar always appearing

### ISSUE THREAD

**Issue by TimJentzsch** [MurdoMaclachlan/website#23]
The padding of the `body` element seems to make it larger than the parent component, resulting in permanent overflow and a scrollbar.

A potential fix could be to set the `body` `padding` to `0` and wrap the rest of the content in a container which applies the padding (I haven't tested that though).

**Comment by MurdoMaclachlan** [comment]
I've been trying to find a fix for this that makes me happy for ages.

The padding is for two purposes; to provide a gap above the header (this works with the suggested solution), and to force the footer to the bottom of the page even when there isn't enough content to push it there (this doesn't work with the suggested solution).

The overflow arises because of the second purpose, which for me personally is the more important. I _tried_ to make it better with `empty.css` on the affected pages, but it doesn't help much.

I'm sure there's a proper way of positioning the footer like this, but I couldn't find out how to do it from searching. All the answers I found were about permanently locking it to display like a banner at the bottom regardless of your position on the page, which both isn't what I want and is something I already know how to do.

**Comment by TimJentzsch** [comment]
Would the following work for you? <https://jsfiddle.net/c4v71z80/24/>

Here I apply the padding to the header, content and footer separately instead of to the entire problem. I think this fixes the issue.

**Comment by MurdoMaclachlan** [comment]
This looks like it's working perfectly from my testing. Thank you! Fix should be merged to production relatively soon. Very satisfying to finally get rid of this bug. 😁
