### ISSUE TITLE
Tab view not controllable by keyboard

### ISSUE THREAD

**Issue by TimJentzsch** [MurdoMaclachlan/website#26]
The tab view (e.g. on <https://murdomaclachlan.github.io/website/pages/projects/videos.html>) is not controllable by keyboard, e.g. you can't change to the other tabs with a keyboard only.
The tabs should be able to get focus from the keyboard and when you press enter it switches to that tab.

My guess is that the problem is caused by the tabs being `a` links without an `href` attribute.
Instead, they should be `button` elements with corresponding click handlers (and maybe key handlers, I forgot if enter sends a click event).

**Comment by MurdoMaclachlan** [comment]
Been forced to kind of hack this, unfortunately.

If I change the `a` elements to `button` elements, the styling breaks completely, and given I'm working within a framework that's doing almost everything for me, I don't know how to fix it.

If I give the `a` elements these properties, `href="#" onclick="return false;"`, then the styling and functionality is retained and it's accessible through the keyboard.

This doesn't make me happy, though, because it's hacky and less transparent about what the tabs are supposed to do than if a `button` was used.

Since my original implementation was taken straight from the Bulma docs, I'm going to take this issue upstream anyway, so maybe I'll get some advice there. For now I'll just go with the hack since it at least makes the site functionally accessible.

Thanks for doing all this testing, by the way! I feel a bit stupid for forgetting keyboard navigation is a thing. :sweat_smile:
